### ISSUE TITLE
Compile error VS 2017 Community

### ISSUE THREAD

**Issue by dza6549** [numediart/ofxMotionMachine#6]
Hi

this application is very interesting. I have VS 2017 Community. I have downloaded and installed SDK 8.1 as it would not compile. Now I have new errors. It looks like more dependencies from OF are required. Could you please advise? Let me know if I can provide further info. Thanks

![errors](https://user-images.githubusercontent.com/27390320/31217944-67e82782-aa04-11e7-888b-fc0f7a3df4ab.png)

**Comment by sohaib-l** [comment]
Hi @dza6549,

Did you copy both of **libs** and **export** folders from openframwroks main folder to [MotionMachine Folder]/libs/oF/?

<img src="https://user-images.githubusercontent.com/3787230/31218881-eb804e42-a9bb-11e7-988c-4e1060d886a3.png" width="200" height="400" />

Check this and let us know!

**Comment by dza6549** [comment]
Wow! Thanks for the rapid response. Yes I followed the install video.

![errors2](https://user-images.githubusercontent.com/27390320/31219282-8903d070-aa08-11e7-81c5-02f533a1fa5a.png)

**Comment by sohaib-l** [comment]
I have just downloaded the files and started everything from the beginning and it is working.
There are few things you need to take into account. You need to use VS2015. So go to the properties of the three projects and specify in the platform Toolset: Visual Studio 2015 (v140) (Figure below). If you don't have it, you need to install VS2015, express version works. (steps I followed (very bad quality, sorry): https://www.youtube.com/watch?v=d8CF9ibBW_g)

![moma](https://user-images.githubusercontent.com/3787230/31221861-56c8ad58-a9c5-11e7-903c-ca7d7720c328.PNG)

**Comment by dza6549** [comment]
Thanks @sohaib-l again for being so quick with helpful suggestions. I have 2017. There is no option for 2015. I tried inherit but error.

![errors4](https://user-images.githubusercontent.com/27390320/31222555-3462efd2-aa13-11e7-8fed-3877eaaf69cb.png)

I will see if I can get 2015 installed 

![errors3](https://user-images.githubusercontent.com/27390320/31222385-a31a437c-aa12-11e7-9025-f4656cb6237a.png)

Thanks

**Comment by dza6549** [comment]
MS does not want me to install 2015 :) I'll see if I can get MM working on the Mac. Thank you for your time today.

![errors5](https://user-images.githubusercontent.com/27390320/31223127-0ac3570a-aa15-11e7-9fe3-2021543d018d.png)

**Comment by dza6549** [comment]
@sohaib-l Is it possible for you to release a MS binary .exe?

**Comment by titsitits** [comment]
Hi,

Actually you don't need to install VS2015, you only need to add the v140 toolset to your VS2017. To do so, you can run the VS2017 installer (download it [here ](https://www.visualstudio.com/fr/thank-you-downloading-visual-studio/?sku=Community&rel=15)if you don't have it anymore), then click the button "modify" (approve the update of VS2017 if needed), and then check the box for the v140 toolset.

Good luck, tell us if it worked ;)

![image](https://user-images.githubusercontent.com/6042752/31225712-93fe6a06-a9d3-11e7-9f29-1d0f773e778a.png)
![image](https://user-images.githubusercontent.com/6042752/31225728-a9ed093a-a9d3-11e7-88d4-964d35c448db.png)

**Comment by dza6549** [comment]
@titsitits thanks! It works!

I just watched Tutorial 2. Is the only way to load an animation file by changing the source code and recompiling? This is the only way I can see to load a new file to change the source code and build again.

Also what are the supported file formats? FBX does not seem to work. I can get c3d to work.

How to import a sequence of animation like your Overview and Possibilities video? Nicolas d'Alessandro talks about a Tutorial 3. Is a tutorial 3 available yet.

This is a great tool for feature extraction. I would like to go further.

@sohaib-l, @titsitits Thanks very much for your quick and helpful responses.

**Comment by titsitits** [comment]
@dza6549,

Concerning tutorials, Nicolas made nice introductive videos, and I made code tutorials that I encourage you to check [here](https://github.com/numediart/MotionMachine/tree/master/apps/examples). (I consent it might be confusing to call them both "tutorials" with the same number...).
Anyway, the third tuto example [here ](https://github.com/numediart/MotionMachine/tree/master/apps/examples/mmTutorial_3_TinyExample)is a tiny example showing how to use drag-and-drop in two lines of codes.
Otherwise you can use the dragevent method of openframeworks, or the file dialog (example see [here](https://github.com/openframeworks/openFrameworks/tree/master/examples/input_output/fileOpenSaveDialogExample). The MotionMachine is based on OF and armadillo so that you can use both their possibilities in our framework.

The first two tuto examples explain a bit more the working of motionmachine, datatypes and data manipulation.

Concerning supported formats, FBX is not supported (yet). BVH is supported and is maybe the closest file type I guess, if you can export in this format, or convert FBX to BVH... I don't know well animation file formats (I'm more on Qualisys/C3D/Visual3D stuff) but I will ask a collegue is he has another solution for using FBX in MotionMachine.

**Comment by titsitits** [comment]
Hi again,

Concerning FBX, the simplest way would indeed be converting your file (with motionbuilder for instance) to BVH. Otherwise, if you have time and a lot of motivation, you can try loading your file in OF with something like [ofxFBX](https://github.com/NickHardeman/ofxFBX), and extract data in a MoMa::Track...
