### ISSUE TITLE
ProjectGenerator for windows

### ISSUE THREAD

**Issue by LGEx** [numediart/ofxMotionMachine#9]
Hi
Your work is very interesting. Congratulations and many thanks for the contribution.
I have installed VS2015, version 0.9.8 of OpenFrameworks and MotionMachine repository in folder addons in windows 10. **How do I generate a motionMachine project for windows?**
of_v0.9.8_vs_release \ addons \ ofxMotionMachine \ projectGenerator - * - MoMa \ projectGenerator for windos operating system is not available.
Waiting for some guidance. Thank you very much

**Comment by thiravet** [comment]
Hi,

In order to solve your problem, i need to understand it. 
Do you have projectGenerator.exe file in ofxMotionMachine\projectGenerator-vs-moma (https://github.com/numediart/ofxMotionMachine/blob/master/projectGenerator-vs-MoMa/projectGenerator.exe)?
 Did you try to launch it? If there is an error, can you describe it? (this generator should work as OF project generator but it adds automatically the addons dependencies for MoMa and copy .h and .cpp files from MoMa template)

Thanks for this feedback and your encouraging comment

best regards 

Thierry

**Comment by LGEx** [comment]
Hi,
thanks for your prompt response.

> Did you try to launch it? 

Yes, and the result was this
![picture projectgenerator](https://user-images.githubusercontent.com/39305366/40143341-8a190600-5931-11e8-98bc-0b4f01c9c699.jpg)

After clicking on _Close_, the result was this

![picture missing addons](https://user-images.githubusercontent.com/39305366/40143675-736eee64-5932-11e8-8d39-5aa64f57eaf6.jpg)

The plugins dependencies were installed correctly? If not, how can I overcome this situation?

When I want to load the baseline example, the file structure is displayed as follows. Is this correct?

![visualizacion del mmempyexample](https://user-images.githubusercontent.com/39305366/40144348-a6bbce52-5934-11e8-9b4c-31e59e694672.jpg)

Thanks for your answers.

best regards.

Leo

**Comment by thiravet** [comment]
Can you try to replace repository name ofxMotionMachine-master by ofxMotionMachine?. I think it's the problem

best regards 

Thierry

**Comment by thiravet** [comment]
It's with pleasure.
Don't hesitate to give us your feedback about MotionMachine.

Best regards 

Thierry
